on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install mkdocs-material
      - run: cd home && mkdocs gh-deploy --force
    - name: create-json
    id: create-json
    uses: jsdaniell/create-json@1.1.2
    with:
      name: "CNAME"
      json: 'wiki.kome-lab.net'